"""added tasks_for column to request

Revision ID: effefe4dac03
Revises: bd7caeb72cc8
Create Date: 2021-10-16 14:06:45.470453

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'effefe4dac03'
down_revision = 'bd7caeb72cc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('request', sa.Column('tasks_for', sa.String(length=64), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('request', 'tasks_for')
    # ### end Alembic commands ###
